[build]
    publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_VERSION = "0.83.1"
    HUGO_ENV = "production"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.83.1"
    HUGO_ENV = "production"
[context.branch-deploy.environment]
    HUGO_VERSION = "0.83.1"
    HUGO_ENV = "production"